# 1) Build stage: използваме официален Maven с JDK 21
FROM maven:3.8.6-jdk-21 AS build

WORKDIR /workspace
COPY . .

RUN mvn -f order-service/pom.xml \
      -pl order-service/container \
      clean package -DskipTests

# 2) Runtime stage: чист JRE 21
FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /workspace/order-service/container/target/*-runner.jar app.jar

USER 1000

ENTRYPOINT ["java","-jar","/app/app.jar"]