quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.username=sa
quarkus.datasource.password=

# Hibernate ORM
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Camel DataSource
quarkus.camel.datasources.myDs.db-kind=h2
quarkus.camel.datasources.myDs.jdbc.url=${quarkus.datasource.jdbc.url}
quarkus.camel.datasources.myDs.username=${quarkus.datasource.username}
quarkus.camel.datasources.myDs.password=${quarkus.datasource.password}